export { default as InputComponent } from './InputComponent/Input.jsx'
export { default as ModalDelete } from "./modal/modal-delete";
export { default as ModalError } from "./modal/modal-error";
export { default as Rightbar } from "./rightbar/rightbar";
export { default as Sidebar } from './sidebar/sidebar';
export { default as Navbar } from "./navbar/navbar";
export { default as Layout } from './layout/layout';
export { default as List } from "./list/list";
export { default as Main } from "./main/main";